# wordpress/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: wordpress
  clusterIP: None
